// AUTO-GENERATED by: yarn db:types
// Do not edit manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      deals: {
        Row: {
          address: string;
          allow_partial: boolean;
          base_mint: string;
          ciphertexts: string;
          created_at: string;
          created_signature: string;
          encryption_key: string;
          expires_at: string;
          indexed_at: string | null;
          nonce: string;
          quote_mint: string;
          settled_at: string | null;
          settled_signature: string | null;
          settlement_ciphertexts: string | null;
          settlement_encryption_key: string | null;
          settlement_nonce: string | null;
          slot: number;
          status: string;
        };
        Insert: {
          address: string;
          allow_partial: boolean;
          base_mint: string;
          ciphertexts: string;
          created_at: string;
          created_signature: string;
          encryption_key: string;
          expires_at: string;
          indexed_at?: string | null;
          nonce: string;
          quote_mint: string;
          settled_at?: string | null;
          settled_signature?: string | null;
          settlement_ciphertexts?: string | null;
          settlement_encryption_key?: string | null;
          settlement_nonce?: string | null;
          slot: number;
          status?: string;
        };
        Update: {
          address?: string;
          allow_partial?: boolean;
          base_mint?: string;
          ciphertexts?: string;
          created_at?: string;
          created_signature?: string;
          encryption_key?: string;
          expires_at?: string;
          indexed_at?: string | null;
          nonce?: string;
          quote_mint?: string;
          settled_at?: string | null;
          settled_signature?: string | null;
          settlement_ciphertexts?: string | null;
          settlement_encryption_key?: string | null;
          settlement_nonce?: string | null;
          slot?: number;
          status?: string;
        };
        Relationships: [];
      };
      offers: {
        Row: {
          address: string;
          ciphertexts: string;
          created_signature: string;
          deal_address: string;
          encryption_key: string;
          indexed_at: string | null;
          nonce: string;
          offer_index: number;
          settled_at: string | null;
          settled_signature: string | null;
          settlement_ciphertexts: string | null;
          settlement_encryption_key: string | null;
          settlement_nonce: string | null;
          slot: number;
          status: string;
          submitted_at: string;
        };
        Insert: {
          address: string;
          ciphertexts: string;
          created_signature: string;
          deal_address: string;
          encryption_key: string;
          indexed_at?: string | null;
          nonce: string;
          offer_index: number;
          settled_at?: string | null;
          settled_signature?: string | null;
          settlement_ciphertexts?: string | null;
          settlement_encryption_key?: string | null;
          settlement_nonce?: string | null;
          slot: number;
          status?: string;
          submitted_at: string;
        };
        Update: {
          address?: string;
          ciphertexts?: string;
          created_signature?: string;
          deal_address?: string;
          encryption_key?: string;
          indexed_at?: string | null;
          nonce?: string;
          offer_index?: number;
          settled_at?: string | null;
          settled_signature?: string | null;
          settlement_ciphertexts?: string | null;
          settlement_encryption_key?: string | null;
          settlement_nonce?: string | null;
          slot?: number;
          status?: string;
          submitted_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "offers_deal_address_fkey";
            columns: ["deal_address"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["address"];
          }
        ];
      };
      raw_events: {
        Row: {
          block_time: string | null;
          event_name: string;
          id: string;
          indexed_at: string | null;
          raw_data: string;
          signature: string;
          slot: number;
        };
        Insert: {
          block_time?: string | null;
          event_name: string;
          id?: string;
          indexed_at?: string | null;
          raw_data: string;
          signature: string;
          slot: number;
        };
        Update: {
          block_time?: string | null;
          event_name?: string;
          id?: string;
          indexed_at?: string | null;
          raw_data?: string;
          signature?: string;
          slot?: number;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
      DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] &
      DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I;
    }
    ? I
    : never
  : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U;
    }
    ? U
    : never
  : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const;
